#!/usr/bin/env bash
set -euo pipefail

# Generate docs/examples.md from etc/*.ixml + etc/*.txt.
# Called by `make examples`. Also prints each example to stdout.

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BIN="${REPO_ROOT}/target/release/txt2data"
ETC="${REPO_ROOT}/etc"
OUT="${REPO_ROOT}/docs/examples.md"

if [[ ! -x "$BIN" ]]; then
  echo "error: build first (make release)" >&2
  exit 1
fi

# Ordered list: slug|title|description
EXAMPLES=(
  "csv|CSV|Multi-row comma-separated values"
  "greeting|Greeting|Match a literal prefix and extract a name"
  "keyvalue|Key-Value|Simple key=value pair"
  "date|Date|ISO 8601 date with fixed-width fields"
  "http|HTTP Request|HTTP request line (method, path, version)"
  "attribute|Attribute Marks|The \`@\` mark produces flat attributes"
  "email|Email Address|Split local and domain parts"
  "url|URL|Decompose scheme, host, and path"
  "hexcolor|Hex Color|Parse CSS hex color into RGB components"
  "semver|Semver|Semantic version with optional pre-release tag"
  "logentry|Log Entry|Structured log with nested timestamp"
  "envfile|Env File|Dotenv-style config (multi-line, exclusion charset)"
  "math|Math Expression|Arithmetic with repetition (\`*\`) for operator chains"
  "ipv4|IPv4 Address|Dotted-quad address with shared \`octet\` rule"
  "pii|PII Scanner|Scan free text for SSNs, phone numbers, and emails"
  "markdown|Markdown|Parse headings and paragraphs from Markdown"
  "address|Postal Address|US mailing address with exclusion charsets"
  "todolist|Todo List|Markdown-style heading + bullet list"
)

# --- Generate docs/examples.md ---

{
  cat <<'HEADER'
# Examples

Every example below is runnable from the CLI and available in the
[browser demo](https://rh-jfuller.github.io/txt2data/).
Grammar and input files live in [`etc/`](../etc/).

HEADER

  # Build TOC
  echo "## Table of contents"
  echo ""
  for entry in "${EXAMPLES[@]}"; do
    IFS='|' read -r slug title desc <<< "$entry"
    anchor=$(echo "$title" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
    echo "- [${title}](#${anchor}) -- ${desc}"
  done
  echo ""
  echo "---"
  echo ""

  # Build sections
  for entry in "${EXAMPLES[@]}"; do
    IFS='|' read -r slug title desc <<< "$entry"
    grammar_file="${ETC}/${slug}.ixml"
    input_file="${ETC}/${slug}.txt"

    grammar=$(<"$grammar_file")
    input=$(<"$input_file")
    json=$("$BIN" -g "$grammar_file" -i "$input_file" -f json)
    xml=$("$BIN" -g "$grammar_file" -i "$input_file" -f xml)

    cat <<EOF
## ${title}

${desc}.

**Grammar** (\`etc/${slug}.ixml\`)

\`\`\`
${grammar}
\`\`\`

**Input** (\`etc/${slug}.txt\`)

\`\`\`
${input}
\`\`\`

**JSON**

\`\`\`json
${json}
\`\`\`

**XML**

\`\`\`xml
${xml}
\`\`\`

---

EOF
  done

  cat <<'FOOTER'
*Generated by `make examples`.*
FOOTER
} > "$OUT"

echo "wrote ${OUT}"

# --- Print examples to stdout ---

for entry in "${EXAMPLES[@]}"; do
  IFS='|' read -r slug title _ <<< "$entry"
  echo "=== ${title} (json) ==="
  "$BIN" -g "${ETC}/${slug}.ixml" -i "${ETC}/${slug}.txt" -f json
  echo ""
  echo "=== ${title} (xml) ==="
  "$BIN" -g "${ETC}/${slug}.ixml" -i "${ETC}/${slug}.txt" -f xml
  echo ""
done
