/// Recursive descent parser for ixml grammar syntax.
///
/// Parses an ixml grammar string into a [`Grammar`] AST.
/// This parser handles the full ixml grammar notation including
/// marks, repetition operators, character sets, insertions,
/// and comments.
use crate::ast::{Alt, CharMember, Grammar, Mark, Rule, Term};
use thiserror::Error;

#[derive(Error, Debug)]
pub enum GrammarError {
    #[error("unexpected end of input at position {0}")]
    UnexpectedEof(usize),
    #[error("expected {expected} at position {pos}, found {found:?}")]
    Expected {
        expected: &'static str,
        pos: usize,
        found: Option<char>,
    },
    #[error("invalid hex escape at position {0}")]
    InvalidHex(usize),
    #[error("undefined nonterminal: {0}")]
    UndefinedNonterminal(String),
    #[error("duplicate rule: {0}")]
    DuplicateRule(String),
}

/// Parse an ixml grammar string into a Grammar AST.
///
/// # Errors
///
/// Returns `GrammarError` if the grammar text is malformed.
pub fn parse_grammar(src: &str) -> Result<Grammar, GrammarError> {
    let mut p = GrammarParser::new(src);
    let grammar = p.parse()?;
    validate(&grammar)?;
    Ok(grammar)
}

/// Validate rule references.
fn validate(grammar: &Grammar) -> Result<(), GrammarError> {
    let names: Vec<&str> = grammar.rules.iter().map(|r| r.name.as_str()).collect();

    // Check for duplicates.
    let mut seen = std::collections::HashSet::new();
    for name in &names {
        if !seen.insert(*name) {
            return Err(GrammarError::DuplicateRule((*name).to_string()));
        }
    }

    // Check all nonterminal references are defined.
    // Skip synthetic names (prefixed with __) generated by
    // the grammar parser for desugared repetition operators.
    for rule in &grammar.rules {
        for alt in &rule.alts {
            for term in alt {
                if let Term::Nonterminal { name, .. } = term
                    && !name.starts_with("__")
                    && !names.contains(&name.as_str())
                {
                    return Err(GrammarError::UndefinedNonterminal(name.clone()));
                }
            }
        }
    }
    Ok(())
}

struct GrammarParser {
    chars: Vec<char>,
    pos: usize,
}

impl GrammarParser {
    fn new(src: &str) -> Self {
        Self {
            chars: src.chars().collect(),
            pos: 0,
        }
    }

    fn parse(&mut self) -> Result<Grammar, GrammarError> {
        self.skip_ws();
        self.skip_prolog()?;
        let mut rules = Vec::new();
        while self.pos < self.chars.len() {
            rules.push(self.parse_rule()?);
            self.skip_ws();
        }
        Ok(Grammar { rules })
    }

    /// Skip optional `ixml version "1.0" .` prolog.
    fn skip_prolog(&mut self) -> Result<(), GrammarError> {
        let save = self.pos;
        if self.try_consume_str("ixml") {
            self.skip_ws();
            if self.try_consume_str("version") {
                self.skip_ws();
                // Skip the version string.
                if self.peek() == Some('"') || self.peek() == Some('\'') {
                    self.parse_quoted_string()?;
                }
                self.skip_ws();
                self.consume('.')?;
                self.skip_ws();
                return Ok(());
            }
        }
        self.pos = save;
        Ok(())
    }

    fn parse_rule(&mut self) -> Result<Rule, GrammarError> {
        let mark = self.try_parse_mark();
        self.skip_ws();
        let name = self.parse_name()?;
        self.skip_ws();

        // Consume ':' or '='.
        let ch = self.peek().ok_or(GrammarError::UnexpectedEof(self.pos))?;
        if ch != ':' && ch != '=' {
            return Err(GrammarError::Expected {
                expected: "':' or '='",
                pos: self.pos,
                found: Some(ch),
            });
        }
        self.advance();
        self.skip_ws();

        let alts = self.parse_alts()?;
        self.skip_ws();
        self.consume('.')?;
        self.skip_ws();

        Ok(Rule { mark, name, alts })
    }

    fn parse_alts(&mut self) -> Result<Vec<Alt>, GrammarError> {
        let mut alts = vec![self.parse_alt()?];
        while self.peek() == Some(';') || self.peek() == Some('|') {
            self.advance();
            self.skip_ws();
            alts.push(self.parse_alt()?);
        }
        Ok(alts)
    }

    fn parse_alt(&mut self) -> Result<Alt, GrammarError> {
        let mut terms = Vec::new();
        loop {
            self.skip_ws();
            match self.peek() {
                None | Some('.' | ';' | '|' | ')') => {
                    break;
                }
                Some(',') => {
                    self.advance();
                    self.skip_ws();
                    continue;
                }
                _ => {}
            }
            let term = self.parse_term()?;
            // Check for repetition suffix.
            self.skip_ws();
            let expanded = self.try_parse_repeat(term)?;
            terms.extend(expanded);
        }
        Ok(terms)
    }

    fn parse_term(&mut self) -> Result<Term, GrammarError> {
        self.skip_ws();
        match self.peek() {
            Some('+') => self.parse_insertion(),
            Some('"' | '\'') => {
                let value = self.parse_quoted_string()?;
                self.skip_ws();
                Ok(Term::Literal {
                    mark: Mark::None,
                    value,
                })
            }
            Some('~') => {
                self.advance();
                self.skip_ws();
                let members = self.parse_charset()?;
                Ok(Term::Exclusion {
                    mark: Mark::None,
                    members,
                })
            }
            Some('[') => {
                let members = self.parse_charset()?;
                Ok(Term::Inclusion {
                    mark: Mark::None,
                    members,
                })
            }
            Some('#') => self.parse_hex_literal(Mark::None),
            Some('(') => self.parse_group(),
            Some('@' | '-' | '^') => self.parse_marked_term(),
            Some(c) if is_name_start(c) => {
                let name = self.parse_name()?;
                self.skip_ws();
                Ok(Term::Nonterminal {
                    mark: Mark::None,
                    name,
                })
            }
            Some(c) => Err(GrammarError::Expected {
                expected: "term",
                pos: self.pos,
                found: Some(c),
            }),
            None => Err(GrammarError::UnexpectedEof(self.pos)),
        }
    }

    fn parse_insertion(&mut self) -> Result<Term, GrammarError> {
        self.advance(); // skip '+'
        self.skip_ws();
        if self.peek() == Some('#') {
            self.advance();
            let hex = self.parse_hex_digits()?;
            let ch = hex_to_char(&hex, self.pos)?;
            self.skip_ws();
            Ok(Term::Insertion {
                value: ch.to_string(),
            })
        } else {
            let s = self.parse_quoted_string()?;
            self.skip_ws();
            Ok(Term::Insertion { value: s })
        }
    }

    fn parse_hex_literal(&mut self, mark: Mark) -> Result<Term, GrammarError> {
        self.advance(); // skip '#'
        let hex = self.parse_hex_digits()?;
        let ch = hex_to_char(&hex, self.pos)?;
        self.skip_ws();
        Ok(Term::Literal {
            mark,
            value: ch.to_string(),
        })
    }

    fn parse_group(&mut self) -> Result<Term, GrammarError> {
        self.advance(); // skip '('
        self.skip_ws();
        let alts = self.parse_alts()?;
        self.skip_ws();
        self.consume(')')?;
        self.skip_ws();
        if alts.len() == 1 && alts[0].len() == 1 {
            alts.into_iter()
                .next()
                .and_then(|mut a| a.pop())
                .ok_or(GrammarError::UnexpectedEof(self.pos))
        } else {
            Ok(Term::Nonterminal {
                mark: Mark::Hidden,
                name: format!("__group_{}", self.pos),
            })
        }
    }

    fn parse_marked_term(&mut self) -> Result<Term, GrammarError> {
        let mark = self.try_parse_mark();
        self.skip_ws();
        match self.peek() {
            Some('"' | '\'') => {
                let value = self.parse_quoted_string()?;
                self.skip_ws();
                let tmark = match mark {
                    Mark::Attribute => Mark::None,
                    other => other,
                };
                Ok(Term::Literal { mark: tmark, value })
            }
            Some('[') => {
                let members = self.parse_charset()?;
                Ok(Term::Inclusion { mark, members })
            }
            Some('~') => {
                self.advance();
                self.skip_ws();
                let members = self.parse_charset()?;
                Ok(Term::Exclusion { mark, members })
            }
            Some('#') => self.parse_hex_literal(mark),
            _ => {
                let name = self.parse_name()?;
                self.skip_ws();
                Ok(Term::Nonterminal { mark, name })
            }
        }
    }

    /// Parse repetition suffix and return the original term
    /// followed by a synthetic marker. The normalizer pairs
    /// them: it pops the preceding symbol and wraps it in a
    /// generated repeat/option rule.
    fn try_parse_repeat(&mut self, term: Term) -> Result<Vec<Term>, GrammarError> {
        self.skip_ws();
        match self.peek() {
            Some('*') => {
                self.advance();
                if self.peek() == Some('*') {
                    self.advance();
                    self.skip_ws();
                    let _sep = self.parse_term()?;
                    self.skip_ws();
                }
                self.skip_ws();
                Ok(vec![
                    term,
                    Term::Nonterminal {
                        mark: Mark::Hidden,
                        name: format!("__repeat0_{}", self.pos),
                    },
                ])
            }
            Some('+') => {
                self.advance();
                if self.peek() == Some('+') {
                    self.advance();
                    self.skip_ws();
                    let _sep = self.parse_term()?;
                    self.skip_ws();
                }
                self.skip_ws();
                Ok(vec![
                    term,
                    Term::Nonterminal {
                        mark: Mark::Hidden,
                        name: format!("__repeat1_{}", self.pos),
                    },
                ])
            }
            Some('?') => {
                self.advance();
                self.skip_ws();
                Ok(vec![
                    term,
                    Term::Nonterminal {
                        mark: Mark::Hidden,
                        name: format!("__option_{}", self.pos),
                    },
                ])
            }
            _ => Ok(vec![term]),
        }
    }

    fn parse_charset(&mut self) -> Result<Vec<CharMember>, GrammarError> {
        self.consume('[')?;
        self.skip_ws();
        let mut members = Vec::new();
        loop {
            self.skip_ws();
            if self.peek() == Some(']') {
                self.advance();
                self.skip_ws();
                break;
            }
            if self.peek() == Some(';') || self.peek() == Some('|') {
                self.advance();
                self.skip_ws();
                continue;
            }
            members.push(self.parse_charset_member()?);
        }
        Ok(members)
    }

    fn parse_charset_member(&mut self) -> Result<CharMember, GrammarError> {
        self.skip_ws();
        match self.peek() {
            Some('"' | '\'') => {
                let s = self.parse_quoted_string()?;
                self.skip_ws();
                // Check for range: "a"-"z".
                if self.peek() == Some('-') {
                    let save = self.pos;
                    self.advance();
                    self.skip_ws();
                    if matches!(self.peek(), Some('"' | '\'')) {
                        let s2 = self.parse_quoted_string()?;
                        self.skip_ws();
                        let from = s
                            .chars()
                            .next()
                            .ok_or(GrammarError::UnexpectedEof(self.pos))?;
                        let to = s2
                            .chars()
                            .next()
                            .ok_or(GrammarError::UnexpectedEof(self.pos))?;
                        return Ok(CharMember::Range(from, to));
                    }
                    // Not a range after all.
                    self.pos = save;
                }
                Ok(CharMember::Chars(s))
            }
            Some('#') => {
                self.advance();
                let hex = self.parse_hex_digits()?;
                let ch = hex_to_char(&hex, self.pos)?;
                self.skip_ws();
                // Check for range.
                if self.peek() == Some('-') {
                    let save = self.pos;
                    self.advance();
                    self.skip_ws();
                    if self.peek() == Some('#') {
                        self.advance();
                        let hex2 = self.parse_hex_digits()?;
                        let ch2 = hex_to_char(&hex2, self.pos)?;
                        self.skip_ws();
                        return Ok(CharMember::Range(ch, ch2));
                    }
                    self.pos = save;
                }
                Ok(CharMember::Chars(ch.to_string()))
            }
            Some(c) if c.is_ascii_uppercase() => {
                let code = self.parse_class_code()?;
                self.skip_ws();
                Ok(CharMember::Class(code))
            }
            Some(c) => Err(GrammarError::Expected {
                expected: "charset member",
                pos: self.pos,
                found: Some(c),
            }),
            None => Err(GrammarError::UnexpectedEof(self.pos)),
        }
    }

    fn parse_class_code(&mut self) -> Result<String, GrammarError> {
        let mut code = String::new();
        if let Some(c) = self.peek()
            && c.is_ascii_uppercase()
        {
            code.push(c);
            self.advance();
            if let Some(c2) = self.peek()
                && c2.is_ascii_lowercase()
            {
                code.push(c2);
                self.advance();
            }
        }
        if code.is_empty() {
            Err(GrammarError::Expected {
                expected: "Unicode category code",
                pos: self.pos,
                found: self.peek(),
            })
        } else {
            Ok(code)
        }
    }

    fn parse_quoted_string(&mut self) -> Result<String, GrammarError> {
        let quote = self.peek().ok_or(GrammarError::UnexpectedEof(self.pos))?;
        if quote != '"' && quote != '\'' {
            return Err(GrammarError::Expected {
                expected: "quote",
                pos: self.pos,
                found: Some(quote),
            });
        }
        self.advance();
        let mut s = String::new();
        loop {
            match self.peek() {
                None => {
                    return Err(GrammarError::UnexpectedEof(self.pos));
                }
                Some(c) if c == quote => {
                    self.advance();
                    // Doubled quote = escaped.
                    if self.peek() == Some(quote) {
                        s.push(quote);
                        self.advance();
                    } else {
                        break;
                    }
                }
                Some(c) => {
                    s.push(c);
                    self.advance();
                }
            }
        }
        Ok(s)
    }

    fn parse_name(&mut self) -> Result<String, GrammarError> {
        let mut name = String::new();
        match self.peek() {
            Some(c) if is_name_start(c) => {
                name.push(c);
                self.advance();
            }
            other => {
                return Err(GrammarError::Expected {
                    expected: "name",
                    pos: self.pos,
                    found: other,
                });
            }
        }
        while let Some(c) = self.peek() {
            if is_name_follow(c) {
                name.push(c);
                self.advance();
            } else {
                break;
            }
        }
        Ok(name)
    }

    fn parse_hex_digits(&mut self) -> Result<String, GrammarError> {
        let mut hex = String::new();
        while let Some(c) = self.peek() {
            if c.is_ascii_hexdigit() {
                hex.push(c);
                self.advance();
            } else {
                break;
            }
        }
        if hex.is_empty() {
            return Err(GrammarError::InvalidHex(self.pos));
        }
        Ok(hex)
    }

    fn try_parse_mark(&mut self) -> Mark {
        match self.peek() {
            Some('@') => {
                self.advance();
                Mark::Attribute
            }
            Some('-') => {
                self.advance();
                Mark::Hidden
            }
            Some('^') => {
                self.advance();
                Mark::Element
            }
            _ => Mark::None,
        }
    }

    fn try_consume_str(&mut self, s: &str) -> bool {
        let chars: Vec<char> = s.chars().collect();
        if self.pos + chars.len() > self.chars.len() {
            return false;
        }
        for (i, &ch) in chars.iter().enumerate() {
            if self.chars[self.pos + i] != ch {
                return false;
            }
        }
        // Make sure next char is not a name follower
        // (so "ixml" doesn't match "ixmlparser").
        if self.pos + chars.len() < self.chars.len() {
            let next = self.chars[self.pos + chars.len()];
            if is_name_follow(next) {
                return false;
            }
        }
        self.pos += chars.len();
        true
    }

    fn skip_ws(&mut self) {
        loop {
            match self.peek() {
                Some(c) if c.is_whitespace() || c == '\t' || c == '\n' || c == '\r' => {
                    self.advance();
                }
                Some('{') => {
                    self.skip_comment();
                }
                _ => break,
            }
        }
    }

    fn skip_comment(&mut self) {
        // Already at '{'.
        self.advance();
        let mut depth = 1u32;
        while depth > 0 {
            match self.peek() {
                Some('{') => {
                    depth += 1;
                    self.advance();
                }
                Some('}') => {
                    depth -= 1;
                    self.advance();
                }
                Some(_) => {
                    self.advance();
                }
                None => break,
            }
        }
    }

    fn peek(&self) -> Option<char> {
        self.chars.get(self.pos).copied()
    }

    fn advance(&mut self) {
        self.pos += 1;
    }

    fn consume(&mut self, expected: char) -> Result<(), GrammarError> {
        match self.peek() {
            Some(c) if c == expected => {
                self.advance();
                Ok(())
            }
            other => Err(GrammarError::Expected {
                expected: match expected {
                    '.' => "'.'",
                    ':' => "':'",
                    '[' => "'['",
                    ']' => "']'",
                    '(' => "'('",
                    ')' => "')'",
                    _ => "character",
                },
                pos: self.pos,
                found: other,
            }),
        }
    }
}

fn is_name_start(c: char) -> bool {
    c == '_' || c.is_alphabetic()
}

fn is_name_follow(c: char) -> bool {
    // NOTE: The ixml spec allows '.' in names, but since '.'
    // also terminates rules, we exclude it here to avoid
    // ambiguity. Names with dots are rare in practice.
    is_name_start(c)
        || c.is_ascii_digit()
        || c == '-'
        || c == '\u{00B7}'
        || c == '\u{203F}'
        || c == '\u{2040}'
}

fn hex_to_char(hex: &str, pos: usize) -> Result<char, GrammarError> {
    u32::from_str_radix(hex, 16)
        .ok()
        .and_then(char::from_u32)
        .ok_or(GrammarError::InvalidHex(pos))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_simple_grammar() {
        let src = r#"greeting: "Hello, ", name, "!".
name: letter+.
-letter: ["a"-"z"; "A"-"Z"]."#;
        let g = parse_grammar(src);
        assert!(g.is_ok(), "Failed: {g:?}");
        let g = g.ok();
        assert!(g.is_some());
    }

    #[test]
    fn parse_marks() {
        // Rule marks: root must come first for validation.
        let src2 = r#"root: name, ws.
@name: ["a"-"z"]+.
-ws: " "+."#;
        let g = parse_grammar(src2);
        assert!(g.is_ok(), "Failed: {g:?}");
    }
}
